---

- name: Retrieve Device Types
  uri:
    url: "{{netbox_url}}/api/dcim/device-types/?model={{model.type}}"
    method: GET
    headers:
      Authorization: "Token {{netbox_token}}"
      Accept: 'application/json'
    return_content: yes
    body_format: json
    status_code: [200, 201]
  register: netbox_device_types
  run_once: yes
  tags: device_types

- name: Create Device Types
  uri:
    url: "{{netbox_url}}/api/dcim/device-types/"
    method: POST
    headers:
      Authorization: "Token {{netbox_token}}"
      Accept: 'application/json'
    return_content: yes
    body_format: json
    body:
      model: "{{ model.type }}" # remove the "." from vEOS_4.7 and replace with _
      slug: "{{ model.type | lower | regex_replace('[.]','_')}}" # . is a special char escape it using []
      manufacturer: {name: "{{ model.vendor }}"}
      u_height: "{{ model.u_height | default(1) }}" # if this property does not exist use default value of 1
    status_code: [200, 201]
  run_once: yes
  when:
    - netbox_device_types.json.count == 0
  tags: device_types
